---
title: "04_Conclusions"
author: "Minnie"
date: "2025-10-25"
output: html_document
---

# Performance metric

We used RMSE as our chosen Performance metric as it took into account outliers, which may be significant in our data, while also ensuring accuracy of our model. 
The RMSE is given by : 
$$
\text{RMSE} = \sqrt{ \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 }
$$
Where y_i is the...
\hat{y_i} are our predicted ... 


The differing RMSE values can be seen below for our different models: 

%here we insert a barplot of our differing RMSE values, for lin regression we saw Ridge returned the best RMSE


However, it is worth noting that although we chose RMSE as our chosen metric, there is value in other metrics that aren't captured solely by the RMSE. 

# Comparing our models : 

## Missing data
The 2 models we used that could handle missing data were XGBoost and RandomForests: 

```{r}


```


## Removing missing data

We removed missing data and used Linear regression with regularisation, robust regression and Support Vector machines, the results can be found as follows : 




# Conclusions
Hence, we can conclude that our model with the lowest RMSE, hence ... 

